### ISSUE TITLE
Out of Scope?

### ISSUE THREAD

**Issue by AkiraMAEGAWA** [chriseth/patricia-trie#1]
Hi! I am developing DApps! On searching for merkle tree implementation, I found this nice repo!
When I tried this implementation in Remix, an error following occured.
  

Though the variable `byteSet` is declared just before this line, this is out of scope i think:(
https://github.com/chriseth/patricia-trie/blob/fc3fe6aec817439493a7598f1dfd74ab40f64a71/utils.sol#L62

**Comment by chriseth** [comment]
It seems you are using a 0.5.x compiler with 0.4.x source. I just updated it - it should be working now.

**Comment by AkiraMAEGAWA** [comment]
Thank you for updating!
